name: employee_api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cloud_firestore: ^4.13.1
  employee_api:
    path: ../employee_api
  firebase_auth: ^4.14.1
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
