name: admin_profile_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_converter:
    path: ../json_converter

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0