name: rmpl_hrm_admin
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  admin_profile_api:
    path: packages/admin_profile_api
  admin_profile_api_client:
    path: packages/admin_profile_api_client
  admin_profile_repository:
    path: packages/admin_profile_repository
  attendance_api:
    path: packages/attendance_api
  attendance_api_client:
    path: packages/attendance_api_client
  attendance_repository:
    path: packages/attendance_repository
  authentication_repository:
    path: packages/authentication_repository
  employee_api:
    path: packages/employee_api
  employee_api_client:
    path: packages/employee_api_client
  employee_repository:
    path: packages/employee_repository
  holiday_api:
    path: packages/holiday_api
  holiday_api_client:
    path: packages/holiday_api_client
  holiday_repository:
    path: packages/holiday_repository
  notification_api:
    path: packages/notification_api
  notification_api_client:
    path: packages/notification_api_client
  notification_repository:
    path: packages/notification_repository
  form_inputs:
    path: packages/form_inputs
  leave_api:
    path: packages/leave_api
  leave_api_client:
    path: packages/leave_api_client
  leave_repository:
    path: packages/leave_repository
  flutter_svg: ^2.0.7
  loading_indicator: ^3.1.1
  syncfusion_flutter_charts: ^23.1.40
  table_calendar: ^3.0.9
  rename: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  uuid: ^4.1.0
  month_picker_dialog: ^2.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_storage: ^11.2.8
  cloud_firestore: ^4.9.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  formz: ^0.6.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  validators: ^3.0.0
  flow_builder: ^0.0.9

dev_dependencies:
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
