name: salary_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  employee_repository:
    path: ../employee_repository
  flutter:
    sdk: flutter
  salary_api:
    path: ../salary_api

dev_dependencies:
  very_good_analysis: ^5.1.0
