name: holiday_repository
description: Holiday repositoy domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.1
  equatable: ^2.0.5
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_storage: ^11.5.1
  json_annotation: ^4.8.1
  json_converter:
    path: ../json_converter

dev_dependencies:
  build_runner: ^2.4.6
  firebase_auth_platform_interface: ^7.0.4
  firebase_core_platform_interface: ^5.0.0
  json_serializable: ^6.7.1
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
