name: salary_api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.1
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  salary_api:
    path: ../salary_api

dev_dependencies:
  very_good_analysis: ^5.1.0
