name: authontication_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  meta: ^1.11.0
  cache:
    path: ../cache

dev_dependencies:
  firebase_auth_platform_interface: ^7.0.4
  firebase_core_platform_interface: ^5.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
