name: json_converter
description: JSON converter helper package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.1
  json_annotation: ^4.8.1

dev_dependencies:
  very_good_analysis: ^5.1.0
